### ISSUE TITLE
Allow select options to display different string than value

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/hugo-module-tnd-forms#1]
Currently the list of optoins is a slice of strings:

```yaml
  options:
  - Alabama
  - California
```

will produce
```html
<select name="test">
  <option value="Alabama">Alabama</option>
  <option value="California">California</option>
</select>
```

We need to spec up a UX so user can have something like this:
```html
<select name="test">
  <option value="AL">Alabama</option>
  <option value="CA">California</option>
</select>
```

Golang order map keys by alpha, preventing user from imposing an order so 
```yaml
options:
  al: Alabaa
  ca: California
```
is out of the question.

We could use comma separated strings

```yaml
options:
  - 'al: Alabama'
  - 'ca: California'
```

But this means, no option text could ever contain semi columns...
