### ISSUE TITLE
Add checkboxes type

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/hugo-module-tnd-forms#3]
```yaml
name: Delivery
label: delivery
type: checkboxes
options: 
   - Home
   - Office
   - Nope
```
